"""edit base

Revision ID: 52d1e6eeee20
Revises: 8e38b46ce0ac
Create Date: 2024-07-11 19:32:38.894581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52d1e6eeee20'
down_revision = '8e38b46ce0ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bosses_table', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'list_of_employees', ['employer_id'], ['id'])
        batch_op.drop_column('surname')
        batch_op.drop_column('patronymic')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bosses_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('patronymic', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('surname', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
