"""init

Revision ID: fc6fe227522e
Revises: 
Create Date: 2024-07-21 13:14:30.927833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc6fe227522e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('patronymic', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('start_work_date', sa.DateTime(), nullable=True),
    sa.Column('salary', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subordination_links',
    sa.Column('boss_id', sa.Integer(), nullable=False),
    sa.Column('employer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['boss_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['employer_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('boss_id', 'employer_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subordination_links')
    op.drop_table('employees')
    # ### end Alembic commands ###
